### ISSUE TITLE
Bug on main page with module dependency

### ISSUE THREAD

**Issue by Wonay** [The-Brains/Wolfensheep#19]
> `Uncaught Error: Script error for "dobuki", needed by: scripts/graphics/worldview.js
> http://requirejs.org/docs/errors.html#scripterror
>     at makeError (require.js:5)
>     at HTMLScriptElement.onScriptError (require.js:5)`

 press generate on the main page.

**Comment by Wonay** [comment]
here are some info are gathered to help you: https://help.github.com/articles/using-submodules-with-pages/

**Comment by Wonay** [comment]
I pulled the repo on my laptop. But I dont see the dir which should have the submodule. I dont have /scripts/lib/dok . Try to reclone the repo somewhere else to see it.

**Comment by Wonay** [comment]
I ran `git submodule update --init --recursive` as https://github.com/blog/2104-working-with-submodules says to do but still no dir. the dir is not even here at all.

**Comment by Wonay** [comment]
on the other hands, there are alternative to `git submodule` as you can see here: https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree . But I am not sure that those alternatives works well with `Github Pages`

**Comment by Wonay** [comment]
After merging the last PR, I received an email: 

> from GitHub
> 9:25 PM (0 minutes ago)
> to me 
> The page build failed for the `master` branch with the following error:
> 
> The submodule registered for `./scripts/lib/dok` could not be cloned. Make sure it's using https:// and that it's a public repo. For more information, see https://help.github.com/articles/page-build-failed-invalid-submodule/.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

**Comment by Wonay** [comment]
@jacklehamster

**Comment by jacklehamster** [comment]
Try that last one?

**Comment by Wonay** [comment]
It works!
